POST https://backend-node-postgres.onrender.com/videos
Content-Type: application/json

{
  "title": "node.js",
  "description": "Descrição do teste",
  "duration": 10
}

###

GET https://backend-node-postgres.onrender.com/videos

###

PUT https://backend-node-postgres.onrender.com/videos/28edf9ee-410b-4055-a991-5facbde40744
content-type: application/json

{
  "title": "edited",
  "description": "Descrição atualizada",
  "duration": 20
}

###

DELETE https://backend-node-postgres.onrender.com/videos/68016dc6-08e0-404b-b7e3-5983094a140b